# Publish GitHub Pages site, consisting of API documentation and compiled example PDFs
name: Publish site

on:
  push:
    branches:
      - main

# Overwritten by the individual jobs
permissions: {}

jobs:
  build-site:
    runs-on: ubuntu-latest
    permissions:
      contents: read #  to fetch code (actions/checkout)

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - uses: typst-community/setup-typst@48aeee7543d37f01afd1ffb27307dc277387ba13  # v4.3.1
      with:
        typst-version: 0.14.0

    - name: Create output dir
      # Note: `github-pages-temp` should not exist yet
      run: |
        mkdir github-pages-temp
        mkdir github-pages-temp/examples

    - name: Build API docs
      # TODO: Generate HTML instead of PDF once better supported by Typst
      run: typst compile api-docs.typ github-pages-temp/api-docs.pdf

    - name: Build thesis example
      working-directory: example
      run: typst compile thesis.typ ../github-pages-temp/examples/thesis.pdf

    - name: Build cover example
      working-directory: example
      run: typst compile cover.typ ../github-pages-temp/examples/cover.pdf

    - name: Upload site files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b  # v4.0.0
      with:
        path: github-pages-temp

  # See https://github.com/actions/deploy-pages
  deploy-site:
    needs: build-site

    permissions:
      pages: write
      id-token: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e  # v4.0.5
